# Generated by Django 3.0.4 on 2020-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_auto_20200602_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='review',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
