# Generated by Django 3.0.4 on 2020-06-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_auto_20200602_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='completion_date',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='delivery_date',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
